AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'vendor/bundle/**/*'
    - 'Gemfile'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 130

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Documentation:
    Enabled: false

NumericLiterals:
  MinDigits: 11

Style/TrailingBlankLines:
  Enabled: false

Style/BlockComments:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false